[package]
name = "isla-c"
version = "0.1.0"
authors = ["Alasdair <alasdair.armstrong@cl.cam.ac.uk>"]
edition = "2018"
license = "MIT"

[lib]
name = "isla"
crate-type = ["dylib"]

[dependencies]
libc = "0.2.5"
isla-lib = { path = "../isla-lib" }
