[package]
name = "isla"
version = "0.1.0"
authors = ["Alasdair <alasdair.armstrong@cl.cam.ac.uk>"]
edition = "2018"

[build-dependencies]
lalrpop = "0.17.2"

[dependencies]
lalrpop-util = "0.17.2"
regex = "0.2.1"
num_cpus = "1.10.1"
crossbeam = "0.7.2"
z3 = "0.4.0"
getopts = "0.2.21"

