[package]
name = "isla"
version = "0.1.0"
authors = ["Alasdair <alasdair.armstrong@cl.cam.ac.uk>"]
edition = "2018"
license = "MIT"
readme = "README.md"

[[bin]]
name = "isla-property"
path = "src/property.rs"

[[bin]]
name = "isla-footprint"
path = "src/footprint.rs"

[[bin]]
name = "isla-client"
path = "src/client.rs"

[[bin]]
name = "isla-test"
path = "src/test.rs"

[dependencies]
crossbeam = "0.7.2"
getopts = "0.2.21"
num_cpus = "1.10.1"
toml = "0.5.5"
serde = "1.0.104"
sha2 = "0.8.1"
isla-cat = { path = "isla-cat" }
isla-lib = { path = "isla-lib" }

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
panic = "abort"
