[package]
name = "isla"
version = "0.1.0"
authors = ["Alasdair <alasdair.armstrong@cl.cam.ac.uk>"]
edition = "2018"
license = "MIT"
readme = "README.md"

[build-dependencies]
lalrpop = "0.17.2"

[dependencies]
regex = "1.3.1"
lalrpop-util = "0.17.2"
num_cpus = "1.10.1"
crossbeam = "0.7.2"
z3-sys = "0.5.0"
getopts = "0.2.21"
lazy_static = "1.4.0"
libc = "0.2.5"
isla-smt = { path = "isla-smt" }

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
