[package]
name = "isla"
version = "0.1.0"
authors = ["Alasdair <alasdair.armstrong@cl.cam.ac.uk>"]
edition = "2018"
license = "MIT"
readme = "README.md"

[dependencies]
getopts = "0.2.21"
num_cpus = "1.10.1"
toml = "0.5.5"
isla-lib = { path = "isla-lib" }

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
panic = "abort"
