[package]
name = "isla-lib"
version = "0.1.0"
authors = ["Alasdair <alasdair.armstrong@cl.cam.ac.uk>"]
edition = "2018"
license = "MIT"
readme = "README.md"

[build-dependencies]
lalrpop = "0.17.2"

[dependencies]
regex = "1.3.1"
lalrpop-util = "0.17.2"
crossbeam = "0.7.2"
getopts = "0.2.21"
lazy_static = "1.4.0"
toml = "0.5.5"
isla-smt = { path = "../isla-smt" }
