# This is a config for Sail RISC-V in 64-bit mode

pc = "PC"

# No ifetch semantics for RISC-V
ifetch = "Read_ifetch"

read_exclusives = ["Read_RISCV_reserved", "Read_RISCV_reserved_acquire", "Read_RISCV_reserved_strong_acquire"]
write_exclusives = ["Write_RISCV_conditional", "Write_RISCV_conditional_release", "Write_RISCV_conditional_strong_release"]

[[toolchain]]
name = "macos-aarch64"
os = "macos"
arch = "aarch64"
assembler = "riscv64-elf-as"
objdump = "/opt/homebrew/opt/llvm/bin/llvm-objdump"
nm = "/opt/homebrew/opt/llvm/bin/llvm-nm"
linker = "/opt/homebrew/opt/llvm/bin/ld.lld"

[[toolchain]]
name = "default"
assembler = "riscv64-linux-gnu-as -march=rv64imac"
objdump = "riscv64-linux-gnu-objdump"
linker = "riscv64-linux-gnu-ld"
nm = "riscv64-linux-gnu-nm"

# Currently not used for RISC-V
[mmu]
page_table_base = "0x300000"
page_size = "4096"
s2_page_table_base = "0x300000"
s2_page_size = "4096"

[threads]
base = "0x80100000"
top = "0x80300000"
stride = "0x10000"

[symbolic_addrs]
base = "0x80310000"
top = "0x80410000"
stride = "0x10"

[registers.defaults]

[const_primops]
get_config_print_reg = false

[reads]
Read_RISCV_acquire = "A"
Read_RISCV_strong_acquire = "A"
Read_RISCV_reserved = "X"
Read_RISCV_reserved_acquire = ["A", "X"]
Read_RISCV_reserved_strong_acquire = ["A", "X"]

[writes]
Write_RISCV_release = "L"
Write_RISCV_strong_release = "L"
Write_RISCV_conditional = "X"
Write_RISCV_conditional_release = ["L", "X"]
Write_RISCV_conditional_strong_release = ["L", "X"]

[cache_ops]

[barriers]
Barrier_RISCV_rw_rw = "Fence.rw.rw"
Barrier_RISCV_r_rw = "Fence.r.rw"
Barrier_RISCV_r_r = "Fence.r.r"
Barrier_RISCV_rw_w = "Fence.rw.w"
Barrier_RISCV_w_w = "Fence.w.w"
Barrier_RISCV_w_rw = "Fence.w.rw"
Barrier_RISCV_rw_r = "Fence.rw.r"
Barrier_RISCV_r_w = "Fence.r.w"
Barrier_RISCV_w_r = "Fence.w.r"
Barrier_RISCV_tso = "Fence.tso"
Barrier_RISCV_i = "Fence.i"

